#!/usr/bin/env python3
"""
Unity项目初始化脚本
创建基本的Unity项目结构
"""

import os
import json
from pathlib import Path

def create_unity_project_structure(project_name: str, base_path: str = "."):
    """创建Unity项目基本结构"""
    
    project_path = Path(base_path) / project_name
    project_path.mkdir(parents=True, exist_ok=True)
    
    # 创建标准Unity目录结构
    directories = [
        "Assets",
        "Assets/Scenes",
        "Assets/Scripts",
        "Assets/Scripts/Core",
        "Assets/Scripts/Managers",
        "Assets/Scripts/UI",
        "Assets/Scripts/Utils",
        "Assets/Prefabs",
        "Assets/Prefabs/UI",
        "Assets/Prefabs/Characters",
        "Assets/Prefabs/Environment",
        "Assets/Materials",
        "Assets/Textures",
        "Assets/Models",
        "Assets/Audio",
        "Assets/Audio/Music",
        "Assets/Audio/SFX",
        "Assets/Animations",
        "Assets/Animations/Controllers",
        "Assets/Animations/Clips",
        "Assets/Resources",
        "Assets/Plugins",
        "Assets/Editor",
        "Assets/StreamingAssets",
        "Assets/Gizmos",
        "Packages",
        "ProjectSettings",
        "UserSettings"
    ]
    
    for dir_path in directories:
        (project_path / dir_path).mkdir(parents=True, exist_ok=True)
    
    # 创建.gitignore
    gitignore = '''# Unity generated
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# Visual Studio cache directory
.vs/

# Autogenerated VS/MD/Rider solution and target files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.app

# Crashlytics generated file
crashlytics-build.properties

# Packed Addressables
/[Aa]ssets/[Aa]ddressable[Aa]ssets[Dd]ata/*/*.bin*

# TextMeshPro
/[Aa]ssets/TextMesh*Pro/

# Uncomment for server builds
# /[Aa]ssets/[Ss]treamingAssets/
'''
    
    with open(project_path / ".gitignore", 'w', encoding='utf-8') as f:
        f.write(gitignore)
    
    # 创建README
    readme = f'''# {project_name}

## Overview

This is a Unity project.

## Requirements

- Unity 2021.3 LTS or later
- .NET Standard 2.1

## Setup

1. Open Unity Hub
2. Click "Open" and select this folder
3. Unity will import the project

## Project Structure

```
Assets/
├── Scenes/          # Game scenes
├── Scripts/         # C# scripts
│   ├── Core/        # Core game logic
│   ├── Managers/    # Manager classes
│   ├── UI/          # UI scripts
│   └── Utils/       # Utility classes
├── Prefabs/         # Prefab assets
├── Materials/       # Materials
├── Textures/        # Textures
├── Models/          # 3D models
├── Audio/           # Audio files
├── Animations/      # Animation assets
└── Resources/       # Runtime-loadable assets
```

## Building

1. File > Build Settings
2. Select target platform
3. Click "Build"

## License

[Your License]
'''
    
    with open(project_path / "README.md", 'w', encoding='utf-8') as f:
        f.write(readme)
    
    # 创建基本脚本
    game_manager = '''using UnityEngine;

namespace Game.Core
{
    /// <summary>
    /// Main game manager singleton
    /// </summary>
    public class GameManager : MonoBehaviour
    {
        public static GameManager Instance { get; private set; }
        
        [Header("Settings")]
        [SerializeField] private bool debugMode = false;
        
        private void Awake()
        {
            if (Instance == null)
            {
                Instance = this;
                DontDestroyOnLoad(gameObject);
                Initialize();
            }
            else
            {
                Destroy(gameObject);
            }
        }
        
        private void Initialize()
        {
            Debug.Log("GameManager initialized");
            // Initialize game systems here
        }
        
        public void RestartGame()
        {
            // Restart game logic
        }
        
        public void QuitGame()
        {
            #if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
            #else
            Application.Quit();
            #endif
        }
    }
}
'''
    
    with open(project_path / "Assets" / "Scripts" / "Core" / "GameManager.cs", 'w', encoding='utf-8') as f:
        f.write(game_manager)
    
    # 创建Utils脚本
    utils = '''using UnityEngine;

namespace Game.Utils
{
    /// <summary>
    /// Common utility methods
    /// </summary>
    public static class GameUtils
    {
        /// <summary>
        /// Get a random point within a sphere
        /// </summary>
        public static Vector3 RandomPointInSphere(Vector3 center, float radius)
        {
            return center + Random.insideUnitSphere * radius;
        }
        
        /// <summary>
        /// Check if object is within camera view
        /// </summary>
        public static bool IsVisibleToCamera(Camera camera, Vector3 position)
        {
            Vector3 viewportPoint = camera.WorldToViewportPoint(position);
            return viewportPoint.x >= 0 && viewportPoint.x <= 1 &&
                   viewportPoint.y >= 0 && viewportPoint.y <= 1 &&
                   viewportPoint.z > 0;
        }
        
        /// <summary>
        /// Lerp with smooth damp
        /// </summary>
        public static float SmoothLerp(float current, float target, float speed, float deltaTime)
        {
            return Mathf.Lerp(current, target, 1 - Mathf.Exp(-speed * deltaTime));
        }
    }
}
'''
    
    with open(project_path / "Assets" / "Scripts" / "Utils" / "GameUtils.cs", 'w', encoding='utf-8') as f:
        f.write(utils)
    
    print(f"✅ Unity项目 '{project_name}' 已成功创建于: {project_path}")
    print(f"\n📁 项目结构:")
    print(f"   - Assets/ (资源目录)")
    print(f"   - Packages/ (包管理)")
    print(f"   - ProjectSettings/ (项目设置)")
    print(f"   - README.md (项目说明)")
    print(f"   - .gitignore (Git忽略规则)")
    print(f"\n🚀 下一步:")
    print(f"   1. 在Unity Hub中打开此文件夹")
    print(f"   2. Unity将导入项目")
    print(f"   3. 开始开发！")

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="初始化Unity项目结构")
    parser.add_argument("project_name", help="项目名称")
    parser.add_argument("--path", default=".", help="项目创建路径")
    
    args = parser.parse_args()
    
    if not args.project_name.replace("_", "").replace("-", "").isalnum():
        print("❌ 错误: 项目名称只能包含字母、数字、下划线和连字符")
        return
    
    create_unity_project_structure(args.project_name, args.path)

if __name__ == "__main__":
    main()
