/**
 * dsh-workspace-enhancer 构建脚本。
 *
 * 自包含构建（不依赖 DSH checkout 内部脚本）：
 *   - Host 半部  src/index.ts          → lib/index.js   (ESM, platform=node)
 *   - Client 半部 src/client/index.ts  → lib/client.js  (IIFE + __ModuleLoader__.load wrapper)
 *
 * CSS Module 处理：esbuild 插件把 `*.module.css` 编译为「默认导出 = 类名映射对象」
 * 的 JS 模块（类名不 hash，与上游一致）。原始 CSS 由 gen-css.mjs 生成的 raw.ts
 * 在入口一次性注入 <style>。
 *
 * Client 外部化 react / react-dom / react/jsx-runtime（由模块加载器运行时解析）；
 * @deepseek-ai/* 也外部化（能力走 ctx 服务）。
 */
import { build } from 'esbuild'
import { mkdirSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

/** 所有 @deepseek-ai/* 包都在运行时解析（不打包进 bundle）。 */
const deepseekExternal = /^@deepseek-ai\//

/** Client 的 react 家族也外部化（加载器解析单个实例）。 */
const reactExternal = ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client']

/** Client bundle 的 ModuleLoader 包装头尾（与 rewind 同款格式）。 */
const CLIENT_BANNER = `/* dsh-workspace-enhancer client bundle — generated by scripts/build.mjs from src/client/ */
window.__ModuleLoader__.load({
  id: "dsh-workspace-enhancer",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
`
const CLIENT_FOOTER = `
module.exports = __dshEnhancerExports;
    return module.exports;
  }
});
`

/** CSS Module → 默认导出类名对象（类名本身，不 hash）。 */
const cssModulePlugin = {
  name: 'dsh-css-module',
  setup(build) {
    build.onLoad({ filter: /\.module\.css$/ }, async (args) => {
      const raw = readFileSync(args.path, 'utf8')
      const classes = [...new Set(
        [...raw.matchAll(/\.([A-Za-z_][A-Za-z0-9_-]*)(?=[\s,{.#])/g)].map((m) => m[1]),
      )]
      const entries = classes.map((c) => `  ${JSON.stringify(c)}: ${JSON.stringify(c)}`)
      return {
        loader: 'js',
        contents: `// CSS Module（由 dsh-css-module 插件生成）
const css = { ${entries.join(',\n')} }
export default css
`,
      }
    })
  },
}

/** 构建 Host 半部。 */
async function buildHost() {
  await build({
    entryPoints: [join(root, 'src/index.ts')],
    outfile: join(root, 'lib/index.js'),
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node20',
    external: ['esbuild', ...reactExternal],
    packages: 'external',
    sourcemap: false,
    logLevel: 'info',
  })
}

/** 构建 Client 半部。 */
async function buildClient() {
  await build({
    entryPoints: [join(root, 'src/client/index.ts')],
    outfile: join(root, 'lib/client.js'),
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    banner: { js: CLIENT_BANNER },
    footer: { js: CLIENT_FOOTER },
    globalName: '__dshEnhancerExports',
    plugins: [cssModulePlugin],
    // 只外部化确定在 client 模块表的运行时单例（react 家族 + primitives +
    // cordis 核心 + 标签特性需要的 settings 域服务）。dsh-util-workspace-path /
    // dsh-client-store 等工具包打进 bundle（官方 web-app 也是内联它们——模块表报
    // missed 即证明不在表内）。settingsScope / settings.plugins.tab 来自
    // dsh-client-ui-settings（运行时服务，必须外部化）。
    external: [
      ...reactExternal,
      '@deepseek-ai/dsh-client-ui-primitives',
      '@deepseek-ai/dsh-client-ui-settings',
      '@deepseek-ai/dsh-client-locale',
      '@deepseek-ai/cordis',
    ],
    sourcemap: false,
    logLevel: 'info',
  })
}

/** 校验产物存在且非空。 */
function verifyOutputs() {
  const paths = [join(root, 'lib/index.js'), join(root, 'lib/client.js')]
  for (const p of paths) {
    const content = readFileSync(p, 'utf8')
    if (content.length === 0) throw new Error(`构建产物为空: ${p}`)
    console.log(`✓ ${p} (${content.length} bytes)`)
  }
}

mkdirSync(join(root, 'lib'), { recursive: true })

await buildHost()
await buildClient()
verifyOutputs()
console.log('构建完成。')
